algoritmo "Soma(Função)"
// Função :
// Autor :
// Data : 02/05/22
// Seção de Declarações 
var
V1, V2, S: Inteiro
Funcao Soma(A, B :inteiro):inteiro
inicio
      Retorne (A+B)
fimfuncao
inicio
// Seção de Comandos 
   Escreva ("Digite o primeiro valor: ")
   Leia (V1)
   Escreva ("Digite o segundo valor: ")
   Leia (V2)
   S <- Soma(V1, V2)
   EscrevaL ("A soma entre ",V1," e ",V2, " é ",S)
   fimalgoritmo
